//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicMonitor.Device.Master
{
    
    internal partial class Resource
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource.manager == null))
                {
                    Resource.manager = new System.Resources.ResourceManager("MagicMonitor.Device.Master.Resource", typeof(Resource).Assembly);
                }
                return Resource.manager;
            }
        }
        internal static nanoFramework.UI.Font GetFont(Resource.FontResources id)
        {
            return ((nanoFramework.UI.Font)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(Resource.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            courierregular10 = -25095,
            ninab = -14709,
            small = 13070,
            comicsansms16 = 18566,
            segoeuiregular12 = 21930,
            MatrixFont = 28174,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            strnSmallFont = -19509,
            strComicSansMS16 = -18892,
            strNinaFont = 10925,
            strCourierRegular10 = 19139,
            strSegoeUIRegular12 = 25622,
        }
    }
}
